ADCとSBCのキャリーが立たない問題を修正
OpenWaseda/kemuide pull request #8
Opened 2017-12-01 04:00 UTC by kumachan-mis

266行目, カッコつけてしまいましたが, 読みにくければ消してください

2017-12-01 04:34 UTC, hikalium commented
このコードが正しい修正になっていることは確認しましたか？
（flagという変数は、じつはもう使われていないはずなので、上記の変更では修正できていないはずです。）
可能であれば、テスト用にコードを作成し、その結果が変更適用前後でどのように変化したかを報告してもらえるとレビューしやすいです。

2017-12-01 04:53 UTC, yasuo-ozu commented
元のソースの242行目でreg[FLAG]を上書きしているので、この変更は意味ありません。

2017-12-01 05:08 UTC, hikalium commented
フラグの変更は、242行目の代入文で実施されています。
なので、そのあたりを修正するのがよいかとおもいます。

2017-12-01 05:17 UTC, yasuo-ozu commented
235行を修正するのが良いです。
別件の修正で224,225行を追加した時に産んでしまったバグです。
224, 225行を消すとそのバグが復活してしまいます。

CFの判定時にvalではなくval1, val2を参照する方法しか私は思いつきません。
もっとエレガントな方法があるとよいのですが。

2017-12-01 05:26 UTC, yasuo-ozu commented
もう少しいうと、
・valはval1, val2が負数である可能性を考慮して計算している
・cfはval1, val2が正数であることを前提として計算した時に9ビット目が変化したかどうかを調べなければならない
という事です。

具体的には、
ADCの場合は (val1 & 0xFF) + (val2 & 0xFF)
SBCの場合は (val1 & 0xFF) - (val2 & 0xFF)
を計算してみて、9ビット目以降が立っているかを調べてCFとすると良いのではないでしょうか。

うまくできればレポートにも書いて自慢できるでしょう。頑張ってください。

2017-12-04 13:10 UTC, hikalium reviewed
少し質問があるのでご確認ください。

2017-12-04 13:10 UTC, hikalium commented on js/kemu.js
> +var KUEChip2Core = /** @class */ (function () {
@classはなぜ追加したのですか？

2017-12-04 13:13 UTC, hikalium commented on js/kemu.js
> +var KUEChip2Core = /** @class */ (function () {
あわわ、ごめんなさい。自動生成でしたね。問題ありません。

2017-12-04 13:52 UTC, hikalium requested changes
修正点を列挙しましたので確認してください。動作が修正されていることは確認できました！

2017-12-04 13:52 UTC, hikalium commented on src/kuechip2.ts
> +					if (opecode == 8) {	// SBC, ADC
// SBC
に修正したほうがよいです。

2017-12-04 13:52 UTC, hikalium commented on src/kuechip2.ts
> +					}else if (opecode == 9) {	// SBC, ADC
// ADC
に修正したほうがよいです。

2017-12-04 13:52 UTC, hikalium commented on src/kuechip2.ts
> +						cf = (valc & ~0xFF) > 0//存在しないはずの9ビット目以降のビット立っていたら桁あふれ
`> 0` より `!= 0`が適切。
（SBCとの対比として。また、valcが負である場合に誤動作の可能性があります。（現状は起こり得ないけれど））

2017-12-04 13:52 UTC, hikalium commented on src/kuechip2.ts
> +						val2c = val2c + (cf ? 1 : 0)//繰り下がりがあったら引く数に1をたす
no semicolon at end of line (下2行も同様です。)

2017-12-04 13:52 UTC, hikalium commented on src/kuechip2.ts
> +					var val1c = val1, val2c = val2, valc;//8ビットまでしかなくて9ビット目以降が全部0のはずの数たち
コメントを「キャリーフラグ計算用」などとするとわかりやすいと思います。

2017-12-04 13:52 UTC, hikalium commented on src/kuechip2.ts
> +						cf = (valc & ~0xFF) == 0//9ビット目以降が立っていなければ桁あふれなしでcf = true
セミコロンがないです。

2017-12-04 13:52 UTC, hikalium commented on src/kuechip2.ts
> +						cf = (valc & ~0xFF) > 0//存在しないはずの9ビット目以降のビット立っていたら桁あふれ
セミコロンがありません。

2017-12-04 13:54 UTC, hikalium commented on src/kuechip2.ts
> +					}else if (opecode == 9) {	// SBC, ADC
247:セミコロンがないです。

2017-12-05 01:38 UTC, hikalium approved these changes

2017-12-05 01:38 UTC, hikalium commented
LGTM. Thanks!

2017-12-05 01:38 UTC, merged